[package]
description = "Derive macros for KDL"
edition = "2024"
license = "Apache-2.0"
name = "kdl-derive"
repository = "https://github.com/SrGaabriel/kdl-derive"
version = "0.1.2"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[dev-dependencies]
kdl = "6.5.0"
